# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb004da3a748aefc163f5dbec81698db0ebea3e55566166fcef62596c5ab797e9adc06c55837cc95f2c48b6d1d8e5f4a2c494c4579da9826530da4208aa4eda4

test:
  secret_key_base: 4f5a04ed919ec70e5893fa4e194af7a19b4fb11b7d3a09b224202c036b750f0443c660e2db13fc50b3369f948ea001475b1e8146e3b8daaf8f526a33daf86b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
